'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5477
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApplication1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _5Stars() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5Stars", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _5StarsBronzew() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5StarsBronzew", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _5StarsSilver() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5StarsSilver", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AniL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AniL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AniR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AniR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Bart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Bronze() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bronze", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Check() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Check", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DexterL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DexterL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DexterR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DexterR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property EIGHT_G() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EIGHT G", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FIVE_G() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FIVE G", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FOUR_G() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FOUR G", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property GOld() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GOld", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property green_plus_sign_md() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("green-plus-sign-md", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MaggieL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaggieL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MaggieR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MaggieR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property muffins() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("muffins", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NINE_G() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NINE G", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Normal1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Normal1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Normal10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Normal10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Normal2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Normal2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Normal3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Normal3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Normal4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Normal4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Normal5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Normal5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Normal6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Normal6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Normal7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Normal7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Normal8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Normal8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Normal9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Normal9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NotCheck() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NotCheck", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ONE_G() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ONE G", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Plus__Orange() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Plus__Orange", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property plus_hi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plus-hi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SEVEN_G() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SEVEN G", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Silver() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Silver", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SIX_G() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SIX G", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SpeedyL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SpeedyL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SpeedyR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SpeedyR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TEN_G() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TEN G", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property THREE_G() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("THREE G", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TorkL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TorkL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TorkR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TorkR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TurboL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurboL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TurboR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurboR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TWO_G() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TWO G", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
